repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      # Run the linter.
      - id: ruff
        name: ruff-linter

      # Run the formatter.
      - id: ruff-format
        name: ruff-format

      # Run isort for sorting imports.
      - id: ruff
        name: ruff-isort
        args: ["--select", "I", "--fix"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: ["--config-file", "pyproject.toml"]

